var d = {base : ""};
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jquery.jqplot.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"shCore.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"shBrushJScript.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"scripts/shBrushXml.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.logAxisRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.canvasTextRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.canvasAxisLabelRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.canvasAxisTickRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.dateAxisRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.categoryAxisRenderer.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.barRenderer.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.pointLabels.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.dateAxisRenderer.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot.dateAxisRenderer.min.js\"><\/script>");  
document.write("<link class=\"include\" rel=\"stylesheet\" type=\"text/css\" href=\"jquery.jqplot.min.css\" />");
document.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"shCoreDefault.min.css\" />");
document.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"shThemejqPlot.min.css\" />"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"m_jqplot.js\"><\/script>"); 
